name = "LSystems"
uuid = "a3e1f8ee-70d8-4c26-a6f5-dc669742461a"
version = "0.1.1"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
JSON3 = "1.14.3"
LinearAlgebra = "1.12.0"
StaticArrays = "1.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]